src: Handle partclone pipefail

diff --git a/bisk b/bisk
--- a/bisk
+++ b/bisk
@@ -1,4 +1,6 @@
-#!/bin/sh
+#!/bin/bash
+
+set -euf
 
 hasbin()
 {
@@ -7,7 +9,6 @@ hasbin()
     exit 1
 }
 
-set -e
 hasbin sgdisk
 hasbin id
 hasbin lsdblk
@@ -15,7 +16,7 @@ hasbin basename
 hasbin dirname
 hasbin cut
 hasbin printf
-set +e
+hasbin partclone.dd
 
 usage()
 {
@@ -78,18 +79,26 @@ save_mbr()
 
 save_blk()
 {
-    _blk="$1"
-    _dirout="$2"
+    _blk_path="$1"
+    _blk_fstype="$2"
+    _dirout="$3"
+    _logfile="$4"
 
-    blk_path="$(echo "$_blk" | cut -d' ' -f1)"
-    blk_fstype="$(echo "$_blk" | cut -d' ' -f2)"
-    blk_name="$(basename "$blk_path")"
+    blk_name="$(basename "$_blk_path")"
 
     partclone_opt="-c"
-    [ -z "$blk_fstype" ] && { blk_fstype="dd"; partclone_opt=; }
+    partclone_fstype="$_blk_fstype"
+    [ -z "$_blk_fstype" ] && { partclone_fstype="dd"; partclone_opt=; }
 
-    partclone."${blk_fstype}" $partclone_opt -d -s "${blk_path}" -N \
+    set -o pipefail
+    partclone."${partclone_fstype}" \
+            $partclone_opt -d3 -N \
+            -s "${_blk_path}" \
+            --logfile "${_logfile}" \
         | gzip -2 > "${_dirout}/${blk_name}.gz"
+    ret="$?"
+    set +o pipefail
+    return "$ret"
 }
 
 save_partitions()
@@ -97,6 +106,7 @@ save_partitions()
     _dev="$1"
     _dirout="$2"
 
+    log_dir="${_dirout}/logs"
     data_blks="$(lsdblk "$_dev")"
 
     if [ -z "$data_blks" ]; then
@@ -104,14 +114,21 @@ save_partitions()
         exit 0
     fi
 
+    mkdir -p "$log_dir"
 
     echo "$data_blks" | while read -r blk; do
+        blk_path="$(echo "$blk" | cut -d' ' -f1)"
+        blk_name="$(basename "$blk_path")"
+        blk_fstype="$(echo "$blk" | cut -d' ' -f2)"
+        [ "$blk_fstype" = "$blk_path" ] && blk_fstype=
+        logfile="${_dirout}/logs/${blk_name}-partclone.log"
+
         # If we fail to clone a block we try with the next one
-        if ! save_blk "$blk" "$_dirout"; then
-            echo "save_blk ${blk}: failed"
+        if ! save_blk "$blk_path" "$blk_fstype" "$_dirout" "$logfile" ; then
+            echo "save_blk '${blk}': failed, log=${logfile}"
             continue
         fi
-        echo "save_blk ${blk}: ok"
+        echo "save_blk '${blk}': ok"
     done
 }
 
